version: '3.4'

services:
  web:
    # Azure Container Registry Image
    # image: 'teetimedock.azurecr.io/tee-time'
    # Dev Image
    image: ex-orb
    build: .
    ports:
      - '80:7777'
    links:
      - teetimedb

    db:
    # Azure Container Registry Image
    # image: 'teetimedock.azurecr.io/mongo'
    # Dev Image
    image: mongo
    ports:
      - '27017:27017'
