version: '3.4'

services:
  web:
    # Azure Container Registry Image
    # image: 'teetimedock.azurecr.io/tee-time'
    # Dev Image
    image: ex-orb
    build: .
    ports:
      - '4200:4200'
    links:
      - db

  db:
    # Azure Container Registry Image
    # image: 'teetimedock.azurecr.io/mongo'
    # Dev Image
    image: mongo
    ports:
      - '27017:27017'
